// Auto-generated by VIP Connect Bot — do not edit manually
// To update, post changes in the event's Slack channel

export const eventConfig = {
  "city": "Tokyo",
  "venue": "メゾン・ド・ユーロン （酒家＿遊龍）, 〒107-0052 東京都港区赤坂4-13-18",
  "capacity": 15,
  "eventTitle": "VIP Connect — Tokyo Leadership Dinner",
  "heroImageUrl": "/venue/long-table.png",
  "heroHeadline": "VIP Connect",
  "heroSubheadline": "Tokyo Leadership Dinner",
  "heroDescription": "An invitation-only gathering for senior leaders shaping the future of commerce and machine learning.",
  "experienceHeadline": "Fifteen leaders.\nA French haven in the heart of Akasaka.\nNo slides.",
  "experienceParagraphs": [
    "A closed-door, invitation-only evening designed for connection, not networking. The group is deliberately small. Senior enough to speak candidly, diverse enough to challenge each other’s assumptions.",
    "The conversation centres on what machine learning is actually changing in commerce. Not the theory, but the reality. What’s working, what’s not, and what the next twelve months look like.",
    "We gather at Mézon de l'Ouragon, where French elegance meets Tokyo sophistication."
  ],
  "agendaItems": [
    {
      "time": "6:00 PM",
      "title": "Arrival & Welcome Drinks",
      "description": "Cocktails in the bar area. Introductions happen naturally when the setting is right and the group is deliberately small."
    },
    {
      "time": "6:30 PM",
      "title": "Executive Session",
      "description": "An unscripted discussion on the future of AI-driven performance, industry evolution, ecosystem collaboration, and what the next twelve months look like."
    },
    {
      "time": "6:45 PM",
      "title": "Dinner",
      "description": "An evening exploring strategic AI and monetization partnerships over exceptional French cuisine."
    },
    {
      "time": "9:00 PM",
      "title": "Event Close",
      "description": "An informal close as the evening winds down."
    }
  ],
  "agendaShort": [
    {
      "time": "6:00 PM",
      "label": "Arrival & welcome drinks"
    },
    {
      "time": "6:30 PM",
      "label": "Executive session"
    },
    {
      "time": "6:45 PM",
      "label": "Dinner"
    },
    {
      "time": "9:00 PM",
      "label": "Event close"
    }
  ],
  "faqItems": [
    {
      "q": "What is Moloco VIP Connect?",
      "a": "An invitation-only, in-person dinner designed for senior leaders across the commerce ecosystem, combining product innovation, industry insight, and high-quality peer discussion."
    },
    {
      "q": "Who is this event for?",
      "a": "Senior executives and leadership in growth, UA, product, monetisation, and performance marketing. We keep the group to around 15 people. Small enough that everyone speaks, diverse enough that you’ll hear something that changes how you think about a problem."
    },
    {
      "q": "Is this a public event / can I bring a +1?",
      "a": "No. Attendance is by invitation only. Invitations may be shared with a relevant colleague or peer, subject to availability. Please check with us first before you share the RSVP link."
    },
    {
      "q": "What should I wear?",
      "a": "Smart casual. Polished but comfortable. Think what you’d wear to dinner with people you want to impress without looking like you tried."
    },
    {
      "q": "Is there a cost to attend?",
      "a": "No. The evening is complimentary for confirmed guests. Dinner, drinks, and the full programme are on Moloco."
    },
    {
      "q": "What about dietary requirements?",
      "a": "メゾン・ド・ユーロン （酒家＿遊龍）, 〒107-0052 東京都港区赤坂4-13-18 accommodates dietary needs: vegetarian, vegan, gluten-free, allergies. Note yours on the registration form and they’ll take care of it."
    }
  ],
  "calendarTitle": "Moloco VIP Connect — Tokyo Leadership Dinner",
  "calendarUidPrefix": "moloco-vip-connect-2026",
  "siteUrl": "https://moloco-event-tokyo-3.vercel.app",
  "slug": "moloco-event-tokyo-3",
  "eventSubtitle": "An evening of strategic partnership possibilities with LINE-Yahoo leadership",
  "venueAddress": "4-13-18 Akasaka, Minato City, Tokyo 107-0052",
  "venueAddressFull": "4-13-18 Akasaka, Minato City, Tokyo 107-0052, Japan",
  "date": "June 10, 2024",
  "dateFull": "Monday, June 10",
  "dateISO": "2024-06-10",
  "calendarDateStart": "20240610T180000",
  "calendarDateEnd": "20240610T210000",
  "time": "6:00 PM",
  "timezone": "Asia/Tokyo",
  "timezoneAbbr": "JST",
  "venueDescription": "Mézon de l'Ouragon stands as one of Tokyo's most distinguished French restaurants, nestled in the sophisticated Akasaka district. This intimate establishment combines classical French culinary traditions with the refined hospitality that defines Japan's dining culture. The restaurant's elegant interior creates an atmosphere of understated luxury, perfect for meaningful business conversations.",
  "venueCapacityNote": "Our private dining room accommodates fifteen guests in an exclusive setting designed for executive-level discussions.",
  "venueDiningNote": "The chef presents contemporary French cuisine with seasonal Japanese influences, paired with an exceptional wine selection.",
  "venueDirections": "Located in Akasaka, the restaurant is a short walk from Akasaka Station (Chiyoda Line) or Akasaka-mitsuke Station (Ginza and Marunouchi Lines). The restaurant is situated in a quiet area of Akasaka, away from the main commercial streets.",
  "venueExperienceLine": "We gather at Mézon de l'Ouragon, where French elegance meets Tokyo sophistication.",
  "dinnerDescription": "An evening exploring strategic AI and monetization partnerships over exceptional French cuisine.",
  "mapsUrl": "https://maps.google.com/?q=4-13-18+Akasaka,+Minato+City,+Tokyo+107-0052,+Japan"
};
